### ISSUE TITLE
Package version

### ISSUE THREAD

**Issue by ioannisPApapadopoulos** [JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl#52]
@dlfivefifty do you mind updating the requirements for `InfiniteArrays`? I am trying to add `SemiclassicalOrthogonalPolynomials`  (on the way to `AlgebraicCurveOrthogonalPolynomials`) but I am getting a clash. 
```

(@v1.6) pkg> add SemiclassicalOrthogonalPolynomials
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package InfiniteArrays [4858937d]:
 InfiniteArrays [4858937d] log:
 ├─possible versions are: 0.0.1-0.12.2 or uninstalled
 ├─restricted to versions 0.12 by EquilibriumMeasures [f387465c], leaving only versions 0.12.0-0.12.2
 │ └─EquilibriumMeasures [f387465c] log:
 │   ├─possible versions are: 0.0.1 or uninstalled
 │   └─EquilibriumMeasures [f387465c] is fixed to version 0.0.1
 └─restricted by compatibility requirements with SemiclassicalOrthogonalPolynomials [291c01f3] to versions: [0.8.0-0.9.5, 0.10.1-0.11.2] — no versions left
   └─SemiclassicalOrthogonalPolynomials [291c01f3] log:
     ├─possible versions are: 0.0.1-0.2.2 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.0.1-0.2.2
```

**Comment by dlfivefifty** [comment]
Will tag soon. 

LS I've invited you to be a "Member", if you set your membership to public you should be able to tag new releases.

**Comment by ioannisPApapadopoulos** [comment]
Thank you! What's the exact process of tagging? Does one simply make the necessary modifications to the required package versions in `Project.toml` and then release a new version?

**Comment by dlfivefifty** [comment]
Hmm the tests aren't passing so I can't tag yet.

Note doing 
```
] add SemiclassicalOrthonalPolynomials#master
```
should work

>  What's the exact process of tagging? Does one simply make the necessary modifications to the required package versions in Project.toml and then release a new version?

1. In Project.toml make sure you've bumped the version. Use (a modified version of) [SEMVAR](https://semver.org): increment the "patch" number (that is `y` in `v0.x.y`) if the change is non-breaking and the "minor" number (that is `x`) if the change is breaking.
2. Make the comment `@JuliaRegistrator register` in the commit. See for example https://github.com/JuliaApproximation/ClassicalOrthogonalPolynomials.jl/commit/771cf31b60bc92855c946531bb41d602fc8c61c7

**Comment by ioannisPApapadopoulos** [comment]
Ok, great, thank you!
