### ISSUE TITLE
Slow lazy multiplication of Jacobi matrices

### ISSUE THREAD

**Issue by ioannisPApapadopoulos** [JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl#77]
I think that the new QR/Cholesky Jacobi matrices have a lazy multiplication that hangs. Does this hang for you? @dlfivefifty @TSGut 

```
using SemiclassicalOrthogonalPolynomials, ClassicalOrthogonalPolynomials
X = jacobimatrix(SemiclassicalJacobi(1.1,0,0,10))
X*X
```

**Comment by ioannisPApapadopoulos** [comment]
For me it seems to hang in `default_blasmul!`

**Comment by TSGut** [comment]
I'll check. In the meantime you should be able to use `ApplyArray(*,X,X)`.

**Comment by dlfivefifty** [comment]
I think we just need the `MemoryLayout` of `QRJacobiData` to be lazy.

**Comment by dlfivefifty** [comment]
https://github.com/JuliaApproximation/ClassicalOrthogonalPolynomials.jl/blob/4789503e1c4900d54be01a55a9d2e511f6530563/src/choleskyQR.jl#L138

Make this `<: LazyMatrix`

**Comment by TSGut** [comment]
I will test that and make a PR

**Comment by TSGut** [comment]
This should be fixed now, let me know if it isn't.
