### ISSUE TITLE
StackOverflow when declaring type

### ISSUE THREAD

**Issue by ioannisPApapadopoulos** [JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl#81]
@dlfivefifty @TSGut 

There is a `StackOverflow` error when declaring the type for `SemiclassicalJacobi`. 

E.g.

```
julia> SemiclassicalJacobi(1.1,0,0,4)[0.2, 1]
1.0

julia> SemiclassicalJacobi{Float64}(1.1,0,0,4)[0.2, 1]
ERROR: StackOverflowError:
```

**Comment by TSGut** [comment]
I'll see if I can reproduce

**Comment by TSGut** [comment]
Whatever was causing this was already fixed in my PR branch, please check that it also fixes it for you.

**Comment by TSGut** [comment]
Ok this should just work now. The master branch was actually dangerously broken as a result of this, I have added a few small tests to avoid this repeating in the future.

**Comment by ioannisPApapadopoulos** [comment]
Thank you!
