### ISSUE TITLE
Broadcasting 0:∞

### ISSUE THREAD

**Issue by ioannisPApapadopoulos** [JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl#95]
Hi @TSGut @dlfivefifty 

Locally I am running into issues in v0.5.4 which are not present in v0.5.3. In v0.5.4 the following lazy broadcasting hangs:

```
using SemiclassicalOrthogonalPolynomials, ClassicalOrthogonalPolynomials
ρ = 0.5
t = inv(1-ρ^2)
Ps = SemiclassicalJacobi.(t,1,1,0:∞)
```

In v0.5.3 then ContinuumArrays is restricted to v0.16.4 and ClassicalOrthogonalPolynomials to v0.11.10.

Does this happen to you/do you know what is going on? Thanks!

**Comment by TSGut** [comment]
Yeah, it's the recent changes in ClassicalOPs.jl that cause this. We made some consistency adjustments that break the function calls, it's a simple fix.

Once my current PR in ClassicalOPs is merged I can sort this package, it shouldn't take me long. @dlfivefifty any chance we could review or merge said PR?

**Comment by ioannisPApapadopoulos** [comment]
Brilliant, thank you @TSGut !!

**Comment by dlfivefifty** [comment]
I've merged and tagged that PR.

But I don't need to review every PR, you could ask @ioannisPApapadopoulos  or @MikaelSlevinsky to do it.

**Comment by TSGut** [comment]
Great, thanks! I will make a PR to fix SemiclassicalOPs today.
